version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db1
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    image: history_buffbot:latest
    ports:
      - "8501:8501"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
volumes:
  pgdata:
